ALTER TABLE users
    ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER'
    CHECK (role IN ('ADMIN', 'CUSTOMER'));

UPDATE users
SET role = 'CUSTOMER'
WHERE role IS NULL OR role = '';
