// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: customers.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    id,
    full_name,
    phone,
    email,
    customer_type,
    created_at,
    updated_at,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, full_name, phone, email, customer_type, created_at, updated_at, is_active
`

type CreateCustomerParams struct {
	ID           uuid.UUID
	FullName     string
	Phone        string
	Email        string
	CustomerType string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsActive     bool
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.Email,
		arg.CustomerType,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsActive,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.CustomerType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const deactivateCustomer = `-- name: DeactivateCustomer :execrows
UPDATE customers
SET
    is_active = FALSE,
    updated_at = $2
WHERE id = $1
  AND is_active = TRUE
`

type DeactivateCustomerParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) DeactivateCustomer(ctx context.Context, arg DeactivateCustomerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateCustomer, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, full_name, phone, email, customer_type, created_at, updated_at, is_active
FROM customers
WHERE LOWER(email) = LOWER($1)
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, lower string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByEmail, lower)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.CustomerType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, full_name, phone, email, customer_type, created_at, updated_at, is_active
FROM customers
WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.CustomerType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, full_name, phone, email, customer_type, created_at, updated_at, is_active
FROM customers
WHERE is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.CustomerType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET
    full_name = $2,
    phone = $3,
    email = $4,
    customer_type = $5,
    updated_at = $6,
    is_active = $7
WHERE id = $1
RETURNING id, full_name, phone, email, customer_type, created_at, updated_at, is_active
`

type UpdateCustomerParams struct {
	ID           uuid.UUID
	FullName     string
	Phone        string
	Email        string
	CustomerType string
	UpdatedAt    time.Time
	IsActive     bool
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.Email,
		arg.CustomerType,
		arg.UpdatedAt,
		arg.IsActive,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.CustomerType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}
