// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ingredients.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (
    id,
    name,
    unit,
    average_cost,
    stock,
    minimum_stock,
    created_at,
    updated_at,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, name, unit, average_cost, stock, minimum_stock, created_at, updated_at, is_active
`

type CreateIngredientParams struct {
	ID           uuid.UUID
	Name         string
	Unit         string
	AverageCost  decimal.Decimal
	Stock        decimal.Decimal
	MinimumStock decimal.Decimal
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsActive     bool
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, createIngredient,
		arg.ID,
		arg.Name,
		arg.Unit,
		arg.AverageCost,
		arg.Stock,
		arg.MinimumStock,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsActive,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.AverageCost,
		&i.Stock,
		&i.MinimumStock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const deactivateIngredient = `-- name: DeactivateIngredient :execrows
UPDATE ingredients
SET
    is_active = FALSE,
    updated_at = $2
WHERE id = $1
  AND is_active = TRUE
`

type DeactivateIngredientParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) DeactivateIngredient(ctx context.Context, arg DeactivateIngredientParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateIngredient, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIngredientByID = `-- name: GetIngredientByID :one
SELECT id, name, unit, average_cost, stock, minimum_stock, created_at, updated_at, is_active
FROM ingredients
WHERE id = $1
`

func (q *Queries) GetIngredientByID(ctx context.Context, id uuid.UUID) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredientByID, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.AverageCost,
		&i.Stock,
		&i.MinimumStock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const listIngredients = `-- name: ListIngredients :many
SELECT id, name, unit, average_cost, stock, minimum_stock, created_at, updated_at, is_active
FROM ingredients
WHERE is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListIngredients(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, listIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unit,
			&i.AverageCost,
			&i.Stock,
			&i.MinimumStock,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngredient = `-- name: UpdateIngredient :one
UPDATE ingredients
SET
    name = $2,
    unit = $3,
    average_cost = $4,
    stock = $5,
    minimum_stock = $6,
    updated_at = $7,
    is_active = $8
WHERE id = $1
RETURNING id, name, unit, average_cost, stock, minimum_stock, created_at, updated_at, is_active
`

type UpdateIngredientParams struct {
	ID           uuid.UUID
	Name         string
	Unit         string
	AverageCost  decimal.Decimal
	Stock        decimal.Decimal
	MinimumStock decimal.Decimal
	UpdatedAt    time.Time
	IsActive     bool
}

func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, updateIngredient,
		arg.ID,
		arg.Name,
		arg.Unit,
		arg.AverageCost,
		arg.Stock,
		arg.MinimumStock,
		arg.UpdatedAt,
		arg.IsActive,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.AverageCost,
		&i.Stock,
		&i.MinimumStock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}
