// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Customer struct {
	ID           uuid.UUID
	FullName     string
	Phone        string
	Email        string
	CustomerType string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsActive     bool
}

type Ingredient struct {
	ID           uuid.UUID
	Name         string
	Unit         string
	AverageCost  decimal.Decimal
	Stock        decimal.Decimal
	MinimumStock decimal.Decimal
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsActive     bool
}

type Order struct {
	ID          uuid.UUID
	CustomerID  uuid.UUID
	Status      string
	Subtotal    decimal.Decimal
	Discount    decimal.Decimal
	Total       decimal.Decimal
	CreatedAt   time.Time
	UpdatedAt   time.Time
	OrderNumber pgtype.Int8
}

type OrderItem struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
	UnitPrice decimal.Decimal
	Subtotal  decimal.Decimal
}

type Payment struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	Amount    decimal.Decimal
	Method    string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Product struct {
	ID          uuid.UUID
	Name        string
	Description string
	ProductType string
	BasePrice   decimal.Decimal
	CostPrice   decimal.Decimal
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ImageUrl    string
	IsPublic    bool
}

type Recipe struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Name      string
	Portions  int32
	CreatedAt time.Time
	UpdatedAt time.Time
	IsActive  bool
}

type RecipeItem struct {
	ID           uuid.UUID
	RecipeID     uuid.UUID
	IngredientID uuid.UUID
	Quantity     decimal.Decimal
	Unit         string
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Email        string
	Username     string
	FullName     string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsActive     bool
	Role         string
}
