// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    id,
    name,
    description,
    product_type,
    base_price,
    cost_price,
    is_active,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, name, description, product_type, base_price, cost_price, is_active, created_at, updated_at
`

type CreateProductParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	ProductType string
	BasePrice   decimal.Decimal
	CostPrice   decimal.Decimal
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ProductType,
		arg.BasePrice,
		arg.CostPrice,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProductType,
		&i.BasePrice,
		&i.CostPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateProduct = `-- name: DeactivateProduct :execrows
UPDATE products
SET
    is_active = FALSE,
    updated_at = $2
WHERE id = $1
  AND is_active = TRUE
`

type DeactivateProductParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) DeactivateProduct(ctx context.Context, arg DeactivateProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateProduct, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, product_type, base_price, cost_price, is_active, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProductType,
		&i.BasePrice,
		&i.CostPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, product_type, base_price, cost_price, is_active, created_at, updated_at
FROM products
WHERE is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ProductType,
			&i.BasePrice,
			&i.CostPrice,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    name = $2,
    description = $3,
    product_type = $4,
    base_price = $5,
    cost_price = $6,
    is_active = $7,
    updated_at = $8
WHERE id = $1
RETURNING id, name, description, product_type, base_price, cost_price, is_active, created_at, updated_at
`

type UpdateProductParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	ProductType string
	BasePrice   decimal.Decimal
	CostPrice   decimal.Decimal
	IsActive    bool
	UpdatedAt   time.Time
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ProductType,
		arg.BasePrice,
		arg.CostPrice,
		arg.IsActive,
		arg.UpdatedAt,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProductType,
		&i.BasePrice,
		&i.CostPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
