// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: recipes.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (
    id,
    product_id,
    name,
    portions,
    created_at,
    updated_at,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, product_id, name, portions, created_at, updated_at, is_active
`

type CreateRecipeParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Name      string
	Portions  int32
	CreatedAt time.Time
	UpdatedAt time.Time
	IsActive  bool
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, createRecipe,
		arg.ID,
		arg.ProductID,
		arg.Name,
		arg.Portions,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsActive,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Portions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const createRecipeItem = `-- name: CreateRecipeItem :one
INSERT INTO recipe_items (
    id,
    recipe_id,
    ingredient_id,
    quantity,
    unit
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, recipe_id, ingredient_id, quantity, unit
`

type CreateRecipeItemParams struct {
	ID           uuid.UUID
	RecipeID     uuid.UUID
	IngredientID uuid.UUID
	Quantity     decimal.Decimal
	Unit         string
}

func (q *Queries) CreateRecipeItem(ctx context.Context, arg CreateRecipeItemParams) (RecipeItem, error) {
	row := q.db.QueryRow(ctx, createRecipeItem,
		arg.ID,
		arg.RecipeID,
		arg.IngredientID,
		arg.Quantity,
		arg.Unit,
	)
	var i RecipeItem
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.IngredientID,
		&i.Quantity,
		&i.Unit,
	)
	return i, err
}

const deactivateRecipe = `-- name: DeactivateRecipe :exec
UPDATE recipes
SET
    is_active = FALSE,
    updated_at = $2
WHERE id = $1
`

type DeactivateRecipeParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) DeactivateRecipe(ctx context.Context, arg DeactivateRecipeParams) error {
	_, err := q.db.Exec(ctx, deactivateRecipe, arg.ID, arg.UpdatedAt)
	return err
}

const getRecipeByID = `-- name: GetRecipeByID :one
SELECT id, product_id, name, portions, created_at, updated_at, is_active
FROM recipes
WHERE id = $1
`

func (q *Queries) GetRecipeByID(ctx context.Context, id uuid.UUID) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipeByID, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Portions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const getRecipeByProductID = `-- name: GetRecipeByProductID :one
SELECT id, product_id, name, portions, created_at, updated_at, is_active
FROM recipes
WHERE product_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetRecipeByProductID(ctx context.Context, productID uuid.UUID) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipeByProductID, productID)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Portions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const getRecipeItemsByRecipeID = `-- name: GetRecipeItemsByRecipeID :many
SELECT id, recipe_id, ingredient_id, quantity, unit
FROM recipe_items
WHERE recipe_id = $1
ORDER BY id
`

func (q *Queries) GetRecipeItemsByRecipeID(ctx context.Context, recipeID uuid.UUID) ([]RecipeItem, error) {
	rows, err := q.db.Query(ctx, getRecipeItemsByRecipeID, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeItem
	for rows.Next() {
		var i RecipeItem
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.IngredientID,
			&i.Quantity,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
SELECT id, product_id, name, portions, created_at, updated_at, is_active
FROM recipes
WHERE is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Portions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipes
SET
    product_id = $2,
    name = $3,
    portions = $4,
    updated_at = $5,
    is_active = $6
WHERE id = $1
RETURNING id, product_id, name, portions, created_at, updated_at, is_active
`

type UpdateRecipeParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Name      string
	Portions  int32
	UpdatedAt time.Time
	IsActive  bool
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, updateRecipe,
		arg.ID,
		arg.ProductID,
		arg.Name,
		arg.Portions,
		arg.UpdatedAt,
		arg.IsActive,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Portions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const updateRecipeItem = `-- name: UpdateRecipeItem :one
UPDATE recipe_items
SET
    ingredient_id = $2,
    quantity = $3,
    unit = $4
WHERE id = $1
RETURNING id, recipe_id, ingredient_id, quantity, unit
`

type UpdateRecipeItemParams struct {
	ID           uuid.UUID
	IngredientID uuid.UUID
	Quantity     decimal.Decimal
	Unit         string
}

func (q *Queries) UpdateRecipeItem(ctx context.Context, arg UpdateRecipeItemParams) (RecipeItem, error) {
	row := q.db.QueryRow(ctx, updateRecipeItem,
		arg.ID,
		arg.IngredientID,
		arg.Quantity,
		arg.Unit,
	)
	var i RecipeItem
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.IngredientID,
		&i.Quantity,
		&i.Unit,
	)
	return i, err
}
